pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'C:\\Users\\mc\\ArcadiaAutomateJenkins'], [$class: 'CleanBeforeCheckout', deleteUntrackedNestedRepositories: true]], userRemoteConfigs: [[credentialsId: 'a176346d-57d6-492b-9d62-4f79d7c700ea', url: 'https://Rukpong@bitbucket.org/arcadiasoftware/arcadia.automate.buffet.git']]])
            }
        }
    }
}
